// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xktyoxighfcskzuohrsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdHlveGlnaGZjc2t6dW9ocnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjEzNTIsImV4cCI6MjA2NDgzNzM1Mn0.SSl4SwfJ4TZrRZjeN1t0CXQUY055VDSukRaqwchB-P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);